# This is to be used with https://github.com/davedash/mysql-anonymous.
# Last updated 2012-11-13; Migration 504
database:
    truncate:
        - abuse_reports
        - access_whitelist
        - addonlogs
        - addon_bluevia
        - addon_purchase
        - addon_inapp
        - addon_inapp_log
        - addon_inapp_notice
        - addon_inapp_payment
        - addon_payment_data
        - api_access
        - approvals
        - auth_group
        - auth_group_permissions
        - auth_message
        - auth_permission
        - auth_user_groups
        - auth_user_user_permissions
        - auth_user
        - bluevia
        - client_data
        - django_admin_log
        - django_session
        - django_site
        - download_counts
        - editor_subscriptions
        - email_preview
        - eventlog
        - fake_email
        - favorites
        - global_stats
        - groups_users
        - hubrsskeys
        - log_activity
        - log_activity_mkt
        - log_activity_addon
        - log_activity_app
        - log_activity_app_mkt
        - log_activity_comment
        - log_activity_comment_mkt
        - log_activity_user
        - log_activity_user_mkt
        - log_activity_version
        - log_activity_version_mkt
        - oauth_nonce
        - oauth_token
        - paypal_checkstatus
        - piston_consumer
        - piston_nonce
        - piston_token
        - refunds
        - ratings_moderation_flags
        - reviewer_scores
        - reviews_moderation_flags
        - stats_addons_collections_counts
        - stats_collections
        - stats_collections_counts
        - stats_collections_share_counts
        - stats_collections_share_counts_totals
        - stats_contributions
        - stats_share_counts
        - stats_share_counts_totals
        - theme_locks
        - update_counts
        - users_install
        - users_history
        - users_versioncomments
        - versioncomments
        - zadmin_reindexing
        - zadmin_siteevent
        - zadmin_siteevent_mkt
    tables:
        addons:
            nullify: [nominationmessage, paypal_id, charity_id]
            random_email: mozilla_contact
            random_int:
                - average_daily_downloads
                - average_daily_users
                - total_contributions
        addons_users:
            delete:
                listed: 0
        blacklisted_guids:
            nullify: comments
        collections:
            delete:
                listed: 0
            random_int: [downloads, weekly_subscribers, monthly_subscribers]
        compatibility_reports:
            random_ip: client_ip
            nullify: [client_os, comments]
        config:
            delete:
                value: "emailchange_secret"
        reviews:
            random_ip: ip_address
        users:
            random_email: email
            nullify:
                - firstname
                - lastname
                - password
                - confirmationcode
                - resetcode
                - resetcode_expires
                - notes
                - last_login_ip
                - last_login_ip
                - last_login_attempt
                - last_login_attempt_ip
                - failed_login_attempts
                - read_dev_agreement
            random_username: [username, nickname]
        users_history:
            random_email: email
        versions:
            nullify: approvalnotes
        users_install:
            random_email: email
        addon_payment_data:
            random_email: email
            nullify:
                - first_name
                - last_name
                - full_name
                - business_name
                - country
                - payerID
                - address_one
                - address_two
                - post_code
                - city
                - state
                - phone
