name: Extract Locales

on:
  push:
    branches:
      - master

jobs:
  extract_locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        uses: ./.github/actions/build-docker

      - name: Cache Dependencies Directory
        uses: ./.github/actions/cache-deps

      - name: Extract Locales
        uses: ./.github/actions/run-docker
        with:
          compose_file: docker-compose.yml
          run: |
            make extract_locales

      - name: Push Locales
        if: github.event_name == 'push'
        shell: bash
        run: |
          make push_locales
